### P.s-> To find the relnship b/w mpg and other attributes

### Structured Data->ML
### D.v->Yes(mpg)->Supervised Learning
### D.V-> Numerical -> Regression

In [65]:
### Data Req and collection
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [66]:
df=pd.read_csv("auto-mpg.csv")

In [67]:
### Data Understanding
df.head()

    mpg  cyl   disp   hp    wt   acc  yr  origin                   car name
0  18.0    8  307.0  130  3504  12.0  70       1  chevrolet chevelle malibu
1  15.0    8  350.0  165  3693  11.5  70       1          buick skylark 320
2  18.0    8  318.0  150  3436  11.0  70       1         plymouth satellite
3  16.0    8  304.0  150  3433  12.0  70       1              amc rebel sst
4  17.0    8  302.0  140  3449  10.5  70       1                ford torino

In [68]:
df.shape

(398, 9)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64
 2   disp      398 non-null    float64
 3   hp        398 non-null    object
 4   wt        398 non-null    int64
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64
 7   origin    398 non-null    int64
 8   car name  398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [70]:
df.describe()

,mpg,cyl,disp,wt,acc,yr,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [71]:
df["origin"]=df["origin"].replace({1:"America",2:"Europe",3:"Asia"})

In [72]:
df.sample(10)

      mpg  cyl   disp   hp    wt   acc  yr   origin                 car name
197  29.0    4   90.0   70  1937  14.2  76   Europe                vw rabbit
115  15.0    8  350.0  145  4082  13.0  73  America  chevrolet monte carlo s
276  21.6    4  121.0  115  2795  15.7  78   Europe               saab 99gle
200  18.0    6  250.0   78  3574  21.0  76  America        ford granada ghia
325  44.3    4   90.0   48  2085  21.7  80   Europe     vw rabbit c (diesel)
390  32.0    4  144.0   96  2665  13.9  82     Asia         toyota celica gt
313  28.0    4  151.0   90  2678  16.5  80  America       chevrolet citation
125  20.0    6  198.0   95  3102  16.5  74  America          plymouth duster
119  20.0    4  114.0   91  2582  14.0  73   Europe               audi 100ls
214  13.0    8  302.0  130  3870  15.0  76  America                ford f108

In [73]:
df=df.drop("car name",axis=1)

In [74]:
df.sample()

      mpg  cyl  disp  hp    wt   acc  yr   origin
266  30.0    4  98.0  68  2155  16.5  78  America

In [75]:
df.dtypes

mpg       float64
cyl         int64
disp      float64
hp         object
wt          int64
acc       float64
yr          int64
origin     object
dtype: object

In [76]:
df["hp"].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [77]:
df["hp"]=df["hp"].replace("?",np.nan)

In [78]:
hp_med=df["hp"].median()
hp_med

93.5

In [79]:
df["hp"]=df["hp"].astype(float)

In [80]:
df["hp"]=df["hp"].replace(np.nan,hp_med)

In [81]:
df.dtypes

mpg       float64
cyl         int64
disp      float64
hp        float64
wt          int64
acc       float64
yr          int64
origin     object
dtype: object

In [82]:
df=pd.get_dummies(df,columns=["origin"])

In [83]:
df.dtypes

mpg               float64
cyl                 int64
disp              float64
hp                float64
wt                  int64
acc               float64
yr                  int64
origin_America       bool
origin_Asia          bool
origin_Europe        bool
dtype: object

In [84]:
df.sample()

,mpg,cyl,disp,hp,wt,acc,yr,origin_America,origin_Asia,origin_Europe
223,15.5,8,318.0,145.0,4140,13.7,77,True,False,False

In [85]:
df.isnull().sum()

mpg               0
cyl               0
disp              0
hp                0
wt                0
acc               0
yr                0
origin_America    0
origin_Asia       0
origin_Europe     0
dtype: int64

In [86]:
X=df.drop("mpg",axis=1)
y=df[["mpg"]]

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)

In [89]:
from sklearn.linear_model import LinearRegression

In [90]:
model_lr=LinearRegression()

In [91]:
model_lr.fit(X_train,y_train)

LinearRegression()

In [92]:
for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, model_lr.coef_[0][idx]))

The coefficient for cyl is -0.19029265581254284
The coefficient for disp is 0.02049158105827898
The coefficient for hp is -0.015179207878318734
The coefficient for wt is -0.006779102374856846
The coefficient for acc is 0.09229496660874403
The coefficient for yr is 0.7811459471231329
The coefficient for origin_America is -1.9679458926111102
The coefficient for origin_Asia is 0.9082565360750954
The coefficient for origin_Europe is 1.059689356536015

In [93]:
intercept = model_lr.intercept_[0]
print("The intercept for our model is {}".format(intercept))

The intercept for our model is -17.605359655525003

In [94]:
model_lr.score(X_train,y_train)

0.8248771719372523

In [95]:
model_lr.score(X_test,y_test)

0.8215938590149721